---
compose_data_directories:
compose_nuke_data_directories: false # keep persistent data by default
compose_nuke_config_directories: false # keep rendered configs by default

compose_file_names:
  - docker-compose.yml
compose_recreate: true

# compose (docker compose v2) or swarm (docker stack deploy)
compose_deployment_mode: compose
compose_stack_file_names: []
