---
# tasks file for roles/network_facts
- name: Filter network facts
  ansible.builtin.setup:
    filter: all_ipv4_addresses

- name: Set workload and storage network IPs
  ansible.builtin.set_fact:
    workload_IP: "{{ ansible_all_ipv4_addresses | ansible.utils.ipaddr(workload_network) | first }}"
    storage_IP: "{{ ansible_all_ipv4_addresses | ansible.utils.ipaddr(storage_network) | first }}"

- name: Verify workload IP is defined
  ansible.builtin.assert:
    that:
      - workload_IP is defined
    fail_msg: "No IP in {{ workload_network }}"
    success_msg: "Selected IP: {{ workload_IP }}"

- name: Verify storage IP is defined
  ansible.builtin.assert:
    that:
      - storage_IP is defined
    fail_msg: "No IP in {{ storage_network }}"
    success_msg: "Selected IP: {{ storage_IP }}"
